# configuration for "develop" branch
-
  branches:
    only:
    - develop
  image: Visual Studio 2019
  configuration: Release
  before_build:
    - ps: >-
        nuget restore
  build:
      parallel: true
      verbosity: quiet
  artifacts:
  - path: 'Installer/bin/Release/RS2014-Mod-Installer.exe'
    name: Installer
  deploy:
  - provider: GitHub
    tag: RSModsInstaller-v$(releaseVersion)
    release: RSModsInstaller-v$(releaseVersion)
    auth_token:
       secure: iGjQAEJQs6QvWb7qRiIvNPKshY1XviAbJcjt+QcIqGBQjcP/MzSejpINlgnm2ZzK
    artifact: Installer
    prerelease: true
