# configuration for "develop" branch
-
  branches:
    only:
    - develop
  image: Visual Studio 2019
  configuration: Release
  before_build:
    - ps: >-
        nuget restore
  build:
      parallel: true
      verbosity: quiet
  on_finish:
  - cmd: >-
       appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/Installer/bin/Release/RS2014-Mod-Installer.exe
