# configuration for "develop" branch
-
  branches:
    only:
    - develop
  image: Visual Studio 2019
  configuration: Release
  before_build:
    - ps: >-
        nuget restore
  build:
      parallel: true
      verbosity: quiet
  on_finish:
  - cmd: >-
       7z a RSMods.zip %APPVEYOR_BUILD_FOLDER%\Release\xinput1_3.dll

       appveyor PushArtifact RSMods.zip
